local M = {}

local alias_width = 12 -- "30 September"

local function path_in_dir(path, dir)
  path = vim.fs.normalize(path)
  dir = vim.fs.normalize(dir)
  return path == dir or path:sub(1, #dir + 1) == dir .. "/"
end

local function noon(year, month, day)
  return os.time({ year = year, month = month, day = day, hour = 12 })
end

local function shift_date(timestamp, days)
  local date = os.date("*t", timestamp)
  return noon(date.year, date.month, date.day + days)
end

local function date_parts(timestamp)
  return os.date("*t", timestamp)
end

local function today()
  local date = date_parts(os.time())
  return noon(date.year, date.month, date.day)
end

local function date_offset(from, to)
  return math.floor(os.difftime(to, from) / 86400 + 0.5)
end

local function count_wiki_links(lines)
  local count = 0
  for _, line in ipairs(lines) do
    for _ in line:gmatch("%[%[[^%]]-%]%]") do
      count = count + 1
    end
  end
  return count
end

function M.setup(opts)
  local vault_path = opts.vault_path
  local daily_notes_folder = opts.daily_notes_folder
  local daily_notes_date_format = opts.daily_notes_date_format
  local calendar_dir = vault_path .. "/calendar"
  local pending_years = {}
  local focus_pending = false

  local function calendar_path(year)
    return string.format("%s/%04d.md", calendar_dir, year)
  end

  local function calendar_year_for_path(path)
    path = vim.fs.normalize(path)
    if vim.fn.fnamemodify(path, ":h") ~= vim.fs.normalize(calendar_dir) then
      return nil
    end
    return tonumber(vim.fn.fnamemodify(path, ":t:r"))
  end

  local function daily_filename(timestamp)
    return os.date(daily_notes_date_format, timestamp)
  end

  local function daily_alias(timestamp)
    local date = date_parts(timestamp)
    return string.format("%02d %s", date.day, os.date("%B", timestamp))
  end

  local function render_calendar(year)
    local lines = {
      "<!-- Generated by Neovim. Do not edit; use :ObsidianCalendarRefresh. -->",
      string.format("# %d Calendar", year),
      "",
    }
    local timestamp = noon(year, 1, 1)
    while date_parts(timestamp).year == year do
      local date = date_parts(timestamp)
      local filename = daily_filename(timestamp)
      local daily_path = string.format("%s/%s/%s.md", vault_path, daily_notes_folder, filename)
      local exists = vim.fn.filereadable(daily_path) == 1
      local daily_lines = exists and vim.fn.readfile(daily_path) or {}
      local alias = daily_alias(timestamp)
      local link = string.format("[[%s/%s|%s]]", daily_notes_folder, filename, alias)
      local visualization = #daily_lines == 0 and "0" or string.rep("#", math.ceil(#daily_lines / 10))
      table.insert(lines, string.format(
        "- [%s] | %s%s | %02d | %s",
        exists and "x" or " ",
        link,
        string.rep(" ", alias_width - #alias),
        count_wiki_links(daily_lines),
        visualization
      ))
      if date.wday == 1 then -- Sunday
        table.insert(lines, "-------------------------------")
      end
      timestamp = shift_date(timestamp, 1)
    end
    return lines
  end

  local function write_calendar(year)
    local path = calendar_path(year)
    local lines = render_calendar(year)
    local old_lines = vim.fn.filereadable(path) == 1 and vim.fn.readfile(path) or nil
    if old_lines and vim.deep_equal(old_lines, lines) then
      return lines
    end
    vim.fn.mkdir(calendar_dir, "p")
    vim.fn.writefile(lines, path)
    return lines
  end

  local function date_at_cursor(bufnr)
    local row = vim.api.nvim_win_get_cursor(0)[1] - 1
    local line = vim.api.nvim_buf_get_lines(bufnr, row, row + 1, false)[1]
    local filename = line and line:match("%[%[" .. vim.pesc(daily_notes_folder) .. "/(%d%d%d%d%-%d%d%-%d%d%-%a)%|")
    if not filename then
      return nil
    end
    local year, month, day = filename:match("^(%d%d%d%d)%-(%d%d)%-(%d%d)")
    return noon(tonumber(year), tonumber(month), tonumber(day))
  end

  local function jump_to_date(bufnr, timestamp)
    local needle = "[[" .. daily_notes_folder .. "/" .. daily_filename(timestamp) .. "|"
    for index, line in ipairs(vim.api.nvim_buf_get_lines(bufnr, 0, -1, false)) do
      if line:find(needle, 1, true) then
        vim.api.nvim_win_set_cursor(0, { index, 0 })
        return true
      end
    end
    return false
  end

  local function update_buffer(bufnr, lines)
    if not vim.api.nvim_buf_is_loaded(bufnr) or vim.deep_equal(vim.api.nvim_buf_get_lines(bufnr, 0, -1, false), lines) then
      return
    end
    local cursor = vim.api.nvim_get_current_buf() == bufnr and vim.api.nvim_win_get_cursor(0) or nil
    vim.bo[bufnr].modifiable = true
    vim.api.nvim_buf_set_lines(bufnr, 0, -1, false, lines)
    vim.bo[bufnr].modified = false
    vim.bo[bufnr].modifiable = false
    vim.bo[bufnr].readonly = true
    if cursor then
      vim.api.nvim_win_set_cursor(0, { math.min(cursor[1], #lines), cursor[2] })
    end
  end

  local function reconcile(bufnr)
    local year = calendar_year_for_path(vim.api.nvim_buf_get_name(bufnr))
    if year then
      update_buffer(bufnr, write_calendar(year))
    end
  end

  local function open_calendar(year, timestamp)
    if vim.fn.filereadable(calendar_path(year)) == 0 then
      write_calendar(year)
    end
    vim.cmd("edit " .. vim.fn.fnameescape(calendar_path(year)))
    if timestamp then
      jump_to_date(0, timestamp)
    end
  end

  local function install_mappings(bufnr)
    if not vim.api.nvim_buf_is_loaded(bufnr) or vim.b[bufnr].obsidian_calendar_mappings then
      return
    end
    vim.b[bufnr].obsidian_calendar_mappings = true
    local function map(lhs, rhs, desc)
      vim.keymap.set("n", lhs, rhs, { buffer = bufnr, desc = desc })
    end
    local function move(days)
      local date = date_at_cursor(bufnr)
      if date then
        jump_to_date(bufnr, shift_date(date, days))
      end
    end
    map("<leader>oj", function() move(7) end, "Next calendar week")
    map("<leader>ok", function() move(-7) end, "Previous calendar week")
    map("<leader>oJ", function()
      local year = calendar_year_for_path(vim.api.nvim_buf_get_name(bufnr))
      if year then open_calendar(year + 1) end
    end, "Next calendar year")
    map("<leader>oK", function()
      local year = calendar_year_for_path(vim.api.nvim_buf_get_name(bufnr))
      if year then open_calendar(year - 1) end
    end, "Previous calendar year")
    map("<leader>oD", function()
      local current_date = today()
      open_calendar(date_parts(current_date).year, current_date)
    end, "Jump to today")
    map("]m", function()
      local date = date_at_cursor(bufnr)
      if date then
        local parts = date_parts(date)
        jump_to_date(bufnr, noon(parts.year, parts.month + 1, 1))
      end
    end, "Next calendar month")
    map("[m", function()
      local date = date_at_cursor(bufnr)
      if date then
        local parts = date_parts(date)
        jump_to_date(bufnr, noon(parts.year, parts.month - 1, 1))
      end
    end, "Previous calendar month")
    map("<CR>", function()
      local date = date_at_cursor(bufnr)
      if date then
        vim.cmd("Obsidian today " .. date_offset(today(), date))
      end
    end, "Open calendar daily note")
  end

  local function prepare_buffer(bufnr)
    if vim.b[bufnr].obsidian_calendar_initialized then
      return
    end
    vim.b[bufnr].obsidian_calendar_initialized = true
    reconcile(bufnr) -- one defensive reconciliation when the calendar is first loaded
    vim.bo[bufnr].readonly = true
    vim.bo[bufnr].modifiable = false
    local current_date = today()
    if calendar_year_for_path(vim.api.nvim_buf_get_name(bufnr)) == date_parts(current_date).year then
      jump_to_date(bufnr, current_date)
    end
    -- autolist installs its Markdown mappings during setup; install ours afterwards.
    vim.schedule(function() install_mappings(bufnr) end)
  end

  local function refresh_year(year)
    local lines = write_calendar(year)
    for _, bufnr in ipairs(vim.api.nvim_list_bufs()) do
      if vim.api.nvim_buf_is_loaded(bufnr) and calendar_year_for_path(vim.api.nvim_buf_get_name(bufnr)) == year then
        update_buffer(bufnr, lines)
      end
    end
  end

  local group = vim.api.nvim_create_augroup("ObsidianCalendars", { clear = true })
  vim.api.nvim_create_autocmd({ "BufReadPost", "BufNewFile", "BufEnter" }, {
    group = group,
    pattern = "*.md",
    callback = function(args)
      if calendar_year_for_path(vim.api.nvim_buf_get_name(args.buf)) then
        prepare_buffer(args.buf)
      end
    end,
  })
  vim.api.nvim_create_autocmd("BufWritePost", {
    group = group,
    pattern = "*.md",
    callback = function(args)
      local path = vim.api.nvim_buf_get_name(args.buf)
      if path_in_dir(path, vault_path .. "/" .. daily_notes_folder) then
        local year = tonumber(vim.fn.fnamemodify(path, ":t"):match("^(%d%d%d%d)%-"))
        if year and not pending_years[year] then
          pending_years[year] = true
          vim.defer_fn(function()
            pending_years[year] = nil
            refresh_year(year)
          end, 250)
        end
      end
    end,
  })
  vim.api.nvim_create_autocmd("FocusGained", {
    group = group,
    callback = function()
      if focus_pending then return end
      focus_pending = true
      vim.defer_fn(function()
        focus_pending = false
        for _, bufnr in ipairs(vim.api.nvim_list_bufs()) do
          if vim.api.nvim_buf_is_loaded(bufnr) and vim.b[bufnr].obsidian_calendar_initialized then
            reconcile(bufnr)
          end
        end
      end, 250)
    end,
  })
  pcall(vim.api.nvim_del_user_command, "ObsidianCalendarRefresh")
  vim.api.nvim_create_user_command("ObsidianCalendarRefresh", function(command)
    refresh_year(tonumber(command.args) or calendar_year_for_path(vim.api.nvim_buf_get_name(0)) or date_parts(today()).year)
  end, { nargs = "?", desc = "Rebuild an Obsidian calendar year" })

  if calendar_year_for_path(vim.api.nvim_buf_get_name(0)) then
    prepare_buffer(0)
  end

  M.open_current = function()
    local current_date = today()
    open_calendar(date_parts(current_date).year)
  end
end

return M
