[ui]
tab-title-account = {{.Account}} {{if .Unread}}({{.Unread}}){{end}}
threading-enabled = true

[compose]
editor = nvim
focus-body = true
empty-subject-warning = true
no-attachment-warning = ^[^>]*attach(ed|ment)

[filters]
text/plain = colorize
text/calendar = calendar
message/delivery-status = colorize
message/rfc822 = colorize
text/html = ! html
.headers = colorize
